### ISSUE TITLE
Query on TLS certs

### ISSUE THREAD

**Issue by alwaysastudent** [rkemery-hashicorp/bash-vault-enterprise-raft-install-script#1]
Do all the nodes share the same TLS certs? 

How are you achieving this? Is this a good practice?

```
vault.crt, vault.key, and ca.crt 
```

**Comment by rkemery-hashicorp** [comment]
Yes, I used a wildcard certificate with a custom certificate authority. For production, wildcards aren't generally recommended because of the conflict with least privilege principle. There are many options though to get the certificates: you could generate self-signed certificates and add those to the trusted anchors on the hosts, use Let's Encrypt, use something like easy-rsa, spin up another Vault cluster and have it issue certificates with the PKI engine with Terraform and the Vault provider, or use the more common tools like Venafi/Route53/Windows Active Directory Certificate Manager etc.
